### ISSUE TITLE
Unable to resolve service for type 'Microsoft.Framework.Notification.INotifier'

### ISSUE THREAD

**Issue by avodovnik** [Microsoft/ApplicationInsights-aspnet5#112]
With a simple app, when I try to add Application Insights, following the Getting Started instructions, I see

> Unable to resolve service for type 'Microsoft.Framework.Notification.INotifier' while attempting to activate 'Microsoft.ApplicationInsights.AspNet.TelemetryInitializers.OperationNameTelemetryInitializer'

Detailed stack trace:

```
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Framework.Notification.INotifier' while attempting to activate 'Microsoft.ApplicationInsights.AspNet.TelemetryInitializers.OperationNameTelemetryInitializer'.
   at Microsoft.Framework.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.ClosedIEnumerableService.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.b__7_0(Type key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ApplicationInsightsExtensions.AddServicesToCollection[T](IServiceProvider serviceProvider, ICollection`1 collection)
   at Microsoft.Framework.DependencyInjection.ApplicationInsightsExtensions.<>c__DisplayClass8_0.b__0(IServiceProvider serviceProvider)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.SingletonCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.<>c__DisplayClass8_0.b__0(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Framework.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Framework.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNet.Builder.UseMiddlewareExtensions.<>c__DisplayClass2_0.b__0(RequestDelegate next)
   at Microsoft.AspNet.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.Start()
   at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.ApplicationStart(IHttpApplication application)
   at Microsoft.AspNet.Loader.IIS.HttpApplicationBase.InvokeApplicationStart(IHttpApplication application)

```

Any ideas on what to check?

**Comment by SergeyKanzhelev** [comment]
I believe you have a mismatch of runtime and Application Insights packages. INotifier was introduced in beta7 as far as I remember. If you are still running beta 6 or earlier - please download earlier version of Application Insights NuGet package.

**Comment by avodovnik** [comment]
Hm, @SergeyKanzhelev 

  "dependencies": {
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta7",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta7",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta7",
    "Microsoft.AspNet.Diagnostics.Abstractions": "1.0.0-beta7",
    "Microsoft.Framework.Logging.Debug": "1.0.0-beta7",
    "Microsoft.ApplicationInsights.AspNet": "1.0.0-beta7",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta7"
  },

**Comment by SergeyKanzhelev** [comment]
I believe this will be resolved with this check-in https://github.com/aspnet/Announcements/issues/68 and you will not have this problem in beta8.

**Comment by SergeyKanzhelev** [comment]
Oh, interesting. So you are using beta7. Let me dig into this

**Comment by SergeyKanzhelev** [comment]
Do you use MVC package in your app?

**Comment by avodovnik** [comment]
No, I don't. 

This is all I have in the app: https://gist.github.com/avodovnik/e432fa135152041f0e86

**Comment by SergeyKanzhelev** [comment]
Ok. I repro-d it with your app. I'll take a look now

**Comment by SergeyKanzhelev** [comment]
Hey @Upendras, override of constructor that we discussed seems to be working. See https://github.com/Microsoft/ApplicationInsights-aspnet5/blob/sergkanz/appWithoutMvc/src/Microsoft.ApplicationInsights.AspNet/TelemetryInitializers/OperationNameTelemetryInitializer.cs#L29. I need to clean up functional tests for empty app I created and we can release a hotfix.

**Comment by SergeyKanzhelev** [comment]
@avodovnik, we have fix in master. You can use compile your own version easily. We will be shipping version of beta8 package soon. For beta 7 for now you can use this workaround: 

1. Insert this line in ```ConfigureServices```:

```
services.AddMvc();
```

2. Include reference to MVC in packages.json:

```
"Microsoft.AspNet.Mvc": "6.0.0-beta7"
```

Sorry for inconvenience. Hope you'll like Application Insights

**Comment by avodovnik** [comment]
@SergeyKanzhelev thanks for the feedback! Looks like it's working - first events sent!
