### ISSUE TITLE
Symbols.NuPkg is not pushed to SymbolSource.org

### ISSUE THREAD

**Issue by olegsych** [Microsoft/ApplicationInsights-aspnet5#40]
Pushing v0.30.0.1-beta of Microsoft.ApplicationInsights.AspNet package to SymbolSource.org failed with an internal error. It is not clear whether the error is caused by the package version, which seemed to be indicated by the error message, or by the new platforms (dnx451 and dnxcore50) it contains.

**Comment by SergKanz** [comment]
Console output:
```
Pushing Microsoft.ApplicationInsights.AspNet 0.31.0-beta4 to the symbol server (http://nuget.gw.symbolsource.org/Public/NuGet)...
PUT http://nuget.gw.symbolsource.org/Public/NuGet/
System.InvalidOperationException: Failed to process request. 'Package submission failed: Unknown custom metadata item kind: 7 Exception: System.Exception: Error while processing pr
oject: 'Microsoft.ApplicationInsights.AspNet'. ---> System.Exception: Error while processing version: '0.31.0-beta4'. ---> System.Exception: Error while processing compilation: 'Re
lease' 'Unsupported,Version=v0.0'. ---> Mi (...). See http://www.symbolsource.org/Public/Home/Help for possible reasons. Fiddler may help diagnosing this error if your client disca
rds attached detailed information.'.
The remote server returned an error: (506) Package submission failed: Unknown custom metadata item kind: 7 Exception: System.Exception: Error while processing project: 'Microsoft.A
pplicationInsights.AspNet'. ---> System.Exception: Error while processing version: '0.31.0-beta4'. ---> System.Exception: Error while processing compilation: 'Release' 'Unsupported
,Version=v0.0'. ---> Mi (...). See http://www.symbolsource.org/Public/Home/Help for possible reasons. Fiddler may help diagnosing this error if your client discards attached detail
ed information... ---> System.Net.WebException: The remote server returned an error: (506) Package submission failed: Unknown custom metadata item kind: 7 Exception: System.Excepti
on: Error while processing project: 'Microsoft.ApplicationInsights.AspNet'. ---> System.Exception: Error while processing version: '0.31.0-beta4'. ---> System.Exception: Error whil
e processing compilation: 'Release' 'Unsupported,Version=v0.0'. ---> Mi (...). See http://www.symbolsource.org/Public/Home/Help for possible reasons. Fiddler may help diagnosing th
is error if your client discards attached detailed information..
   at System.Net.HttpWebRequest.GetResponse()
   at NuGet.RequestHelper.GetResponse()
   at NuGet.HttpClient.GetResponse()
   at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
   --- End of inner exception stack trace ---
   at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
   at NuGet.PackageServer.PushPackageToServer(String apiKey, Func`1 packageStreamFactory, Int64 packageSize, Int32 timeout, Boolean disableBuffering)
   at NuGet.PackageServer.PushPackage(String apiKey, IPackage package, Int64 packageSize, Int32 timeout, Boolean disableBuffering)
   at NuGet.Commands.PushCommand.PushPackageCore(String source, String apiKey, PackageServer packageServer, String packageToPush, TimeSpan timeout)
   at NuGet.Commands.PushCommand.PushPackage(String packagePath, String source, String apiKey, TimeSpan timeout)
   at NuGet.Commands.PushCommand.PushSymbols(String packagePath, TimeSpan timeout)
   at NuGet.Commands.PushCommand.ExecuteCommand()
   at NuGet.Commands.Command.Execute()
   at NuGet.Program.Main(String[] args)
```

Fiddler output:
```
SymbolSource.Gateway.Core.ServerException: Package submission failed:  Unknown custom metadata item kind: 7

Exception:
System.Exception: Error while processing project: 'Microsoft.ApplicationInsights.AspNet'.  ---> System.Exception: Error while processing version: '0.31.0-beta4'.  ---> System.Exception: Error while processing compilation: 'Release' 'Unsupported,Version=v0.0'.  ---> Microsoft.Cci.Pdb.PdbDebugException: Unknown custom metadata item kind: 7
   at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean readStrings)
   at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbReader reader)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, BitAccess bits, Boolean readAllStrings)
   at SymbolSource.Processing.Basic.ManagedSourceExtractor.ReadSources(Stream peStream, Stream pdbStream)
   at SymbolSource.Processing.Basic.Projects.SourceDiscover.<FindSources>d__c.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SymbolSource.Processing.Basic.Projects.AddInfoBuilder.BuildBinaryInfo(IAddInfo addInfo, IList`1 fileInfos, IPackageEntry binaryFileInfo)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SymbolSource.Processing.Basic.Projects.AddInfoBuilder.Build(IPackageFile directoryInfo, IEnumerable`1 includeFiles)
   at SymbolSource.Server.Management.PackageProcessor.ProcessCompilation(IPackageFile content, Version versionEntity, PackageCompilation compilation)
   --- End of inner exception stack trace ---
   at SymbolSource.Server.Management.PackageProcessor.ProcessCompilation(IPackageFile content, Version versionEntity, PackageCompilation compilation)
   at SymbolSource.Server.Management.PackageProcessor.ProcessVersion(User caller, Project projectEntity, PackageVersion version, String packageFormat, Byte[] packageData, Byte[] symbolPackageData)
   --- End of inner exception stack trace ---
   at SymbolSource.Server.Management.PackageProcessor.ProcessVersion(User caller, Project projectEntity, PackageVersion version, String packageFormat, Byte[] packageData, Byte[] symbolPackageData)
   at SymbolSource.Server.Management.PackageProcessor.ProcessProject(User caller, PackageProject package, String packageFormat, Byte[] packageData, Byte[] symbolPackageData)
   --- End of inner exception stack trace ---
   at SymbolSource.Server.Management.PackageProcessor.ProcessProject(User caller, PackageProject package, String packageFormat, Byte[] packageData, Byte[] symbolPackageData)
   at SymbolSource.Server.Management.WebService.UploadPackage(Caller caller, PackageProject package, String packageFormat, Byte[] packageData, Byte[] symbolPackageData)

Log:
4/29/2015 1:47:55 AM (SymbolSource.Server.Management.PackageProcessor) Processing project 'Microsoft.ApplicationInsights.AspNet' in repository 'NuGet'
4/29/2015 1:47:55 AM (SymbolSource.Server.Management.PackageProcessor) Processing version '0.31.0-beta4'
4/29/2015 1:47:55 AM (SymbolSource.Server.Model.StagedDataItem) Storing data for HSS-Package-Normal*Microsoft.ApplicationInsights.AspNet/0.31.0-beta4/270125.zip*application/zip*Microsoft.ApplicationInsights.AspNet.0.31.0-beta4.nupkg...
4/29/2015 1:47:55 AM (SymbolSource.Server.Model.StagedDataItem) Stored data for HSS-Package-Normal*Microsoft.ApplicationInsights.AspNet/0.31.0-beta4/270125.zip*application/zip*Microsoft.ApplicationInsights.AspNet.0.31.0-beta4.nupkg in staging
4/29/2015 1:47:55 AM (SymbolSource.Server.Management.PackageProcessor) Processing compilation 'Release' 'Unsupported,Version=v0.0'


 ---> System.Exception: Unknown custom metadata item kind: 7

Exception:
System.Exception: Error while processing project: 'Microsoft.ApplicationInsights.AspNet'.  ---> System.Exception: Error while processing version: '0.31.0-beta4'.  ---> System.Exception: Error while processing compilation: 'Release' 'Unsupported,Version=v0.0'.  ---> Microsoft.Cci.Pdb.PdbDebugException: Unknown custom metadata item kind: 7
   at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean readStrings)
   at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbReader reader)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, BitAccess bits, Boolean readAllStrings)
   at SymbolSource.Processing.Basic.ManagedSourceExtractor.ReadSources(Stream peStream, Stream pdbStream)
   at SymbolSource.Processing.Basic.Projects.SourceDiscover.<FindSources>d__c.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SymbolSource.Processing.Basic.Projects.AddInfoBuilder.BuildBinaryInfo(IAddInfo addInfo, IList`1 fileInfos, IPackageEntry binaryFileInfo)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SymbolSource.Processing.Basic.Projects.AddInfoBuilder.Build(IPackageFile directoryInfo, IEnumerable`1 includeFiles)
   at SymbolSource.Server.Management.PackageProcessor.ProcessCompilation(IPackageFile content, Version versionEntity, PackageCompilation compilation)
   --- End of inner exception stack trace ---
   at SymbolSource.Server.Management.PackageProcessor.ProcessCompilation(IPackageFile content, Version versionEntity, PackageCompilation compilation)
   at SymbolSource.Server.Management.PackageProcessor.ProcessVersion(User caller, Project projectEntity, PackageVersion version, String packageFormat, Byte[] packageData, Byte[] symbolPackageData)
   --- End of inner exception stack trace ---
   at SymbolSource.Server.Management.PackageProcessor.ProcessVersion(User caller, Project projectEntity, PackageVersion version, String packageFormat, Byte[] packageData, Byte[] symbolPackageData)
   at SymbolSource.Server.Management.PackageProcessor.ProcessProject(User caller, PackageProject package, String packageFormat, Byte[] packageData, Byte[] symbolPackageData)
   --- End of inner exception stack trace ---
   at SymbolSource.Server.Management.PackageProcessor.ProcessProject(User caller, PackageProject package, String packageFormat, Byte[] packageData, Byte[] symbolPackageData)
   at SymbolSource.Server.Management.WebService.UploadPackage(Caller caller, PackageProject package, String packageFormat, Byte[] packageData, Byte[] symbolPackageData)

Log:
4/29/2015 1:47:55 AM (SymbolSource.Server.Management.PackageProcessor) Processing project 'Microsoft.ApplicationInsights.AspNet' in repository 'NuGet'
4/29/2015 1:47:55 AM (SymbolSource.Server.Management.PackageProcessor) Processing version '0.31.0-beta4'
4/29/2015 1:47:55 AM (SymbolSource.Server.Model.StagedDataItem) Storing data for HSS-Package-Normal*Microsoft.ApplicationInsights.AspNet/0.31.0-beta4/270125.zip*application/zip*Microsoft.ApplicationInsights.AspNet.0.31.0-beta4.nupkg...
4/29/2015 1:47:55 AM (SymbolSource.Server.Model.StagedDataItem) Stored data for HSS-Package-Normal*Microsoft.ApplicationInsights.AspNet/0.31.0-beta4/270125.zip*application/zip*Microsoft.ApplicationInsights.AspNet.0.31.0-beta4.nupkg in staging
4/29/2015 1:47:55 AM (SymbolSource.Server.Management.PackageProcessor) Processing compilation 'Release' 'Unsupported,Version=v0.0'



   at SymbolSource.Gateway.Core.GatewayManager.PerformUpload(Caller caller, PackageProject packageProject, String path)
   at SymbolSource.Gateway.Core.GatewayManager.Upload(Caller caller, Stream stream, String company, String repository)
   --- End of inner exception stack trace ---
   at SymbolSource.Gateway.Core.GatewayManager.Upload(Caller caller, Stream stream, String company, String repository)
   at SymbolSource.Gateway.NuGet.Core.Upload16Controller.<>c__DisplayClass1.<Push>b__0()
   at SymbolSource.Gateway.NuGet.Core.Upload16Controller.DoAction(Action action, Int32 successCode, String successMessage)
```

**Comment by SergKanz** [comment]
Looks similar to this one: [aspnet/dnx/issues/1690](https://github.com/aspnet/dnx/issues/1690).

**Comment by olegsych** [comment]
This is likely to be a problem with symbolsource.org. Removing from current iteration because it is out of our control.

**Comment by SergKanz** [comment]
posted question on [google groups](https://groups.google.com/forum/#!topic/symbolsource/iTSfZ57WvnI) and will send an e-mail to symbolsource@symbolsource.org

**Comment by TripleEmcoder** [comment]
Hi everyone and sorry for the trouble! The issue has been resolved. Please try to push again.

**Comment by SergKanz** [comment]
Pushed symbols for 0.31.0-beta4. It is working now. Thanks!

**Comment by olegsych** [comment]
Cool! Did you do it with nuget.exe or is there a direct way to publish to SymbolSource.org?

**Comment by SergKanz** [comment]
nuget.exe. Command like this:
```
nuget.exe push Foo.symbols.nupkg -Source https://nuget.gw.symbolsource.org/Public/NuGet -ApiKey ***
```

**Comment by olegsych** [comment]
Nice. Is the ApiKey for symbolsource.org the same as for Nuget.org?

**Comment by SergKanz** [comment]
It worked for me =)

**Comment by TripleEmcoder** [comment]
The same one, SymbolSource passes the key to nuget.org for verification and allows/disallows uploads according to package ownership.

**Comment by olegsych** [comment]
Sweet! Thanks, @SergKanz and @TripleEmcoder.
